<?php

function inventra_ensure_stock_movements_table(PDO $conn): void
{
    $sql = "
        CREATE TABLE IF NOT EXISTS stock_movements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference VARCHAR(50) NOT NULL UNIQUE,
            product_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            movement_type VARCHAR(10) NOT NULL CHECK (movement_type IN ('in', 'out')),
            quantity INTEGER NOT NULL,
            notes TEXT NULL,
            full_name VARCHAR(150) NULL,
            contact VARCHAR(50) NULL,
            amount_per_piece DECIMAL(10,2) NOT NULL DEFAULT 0,
            total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
            payment_status VARCHAR(10) NOT NULL DEFAULT 'paid' CHECK (payment_status IN ('paid', 'unpaid')),
            payment_method VARCHAR(10) NOT NULL DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card')),
            incoming_status VARCHAR(50) NULL,
            movement_status VARCHAR(50) NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_stock_movements_product
                FOREIGN KEY (product_id) REFERENCES products(id)
                ON DELETE CASCADE
        )
    ";

    $conn->exec($sql);
    $conn->exec('CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id_created_at ON stock_movements (product_id, created_at)');
}

function inventra_generate_stock_reference(): string
{
    return 'STK-' . date('YmdHis') . '-' . strtoupper(bin2hex(random_bytes(2)));
}

function inventra_record_stock_movement(PDO $conn, array $data, int $userId): array
{
    $stockType = trim((string)($data['stock_type'] ?? $data['movement_type'] ?? ''));
    $productId = (int)($data['product_id'] ?? 0);
    $quantity = (int)($data['quantity'] ?? 0);
    $notes = trim((string)($data['notes'] ?? ''));
    $fullName = trim((string)($data['full_name'] ?? $data['person_name'] ?? ''));
    $contact = trim((string)($data['contact'] ?? $data['contact_number'] ?? ''));
    $amountPerPiece = (float)($data['amount_per_piece'] ?? 0);
    $paymentStatus = strtolower(trim((string)($data['payment_status'] ?? 'paid')));
    $paymentMethod = strtolower(trim((string)($data['payment_method'] ?? 'cash')));
    $incomingStatus = trim((string)($data['incoming_status'] ?? ''));

    if (in_array($stockType, ['Stock In', 'stock_in', 'in'], true)) {
        $movementType = 'in';
    } elseif (in_array($stockType, ['Stock Out', 'stock_out', 'out'], true)) {
        $movementType = 'out';
    } else {
        return ['success' => false, 'message' => 'Invalid stock type. Use Stock In or Stock Out.'];
    }

    if ($userId <= 0) {
        return ['success' => false, 'message' => 'Authentication required.'];
    }

    if ($productId <= 0) {
        return ['success' => false, 'message' => 'Product is required.'];
    }

    if ($quantity <= 0) {
        return ['success' => false, 'message' => 'Quantity must be greater than 0.'];
    }

    if ($fullName === '') {
        return ['success' => false, 'message' => 'Full name is required.'];
    }

    if ($contact === '' || !preg_match('/^[0-9+\-\s()]{7,20}$/', $contact)) {
        return ['success' => false, 'message' => 'Valid contact number is required.'];
    }

    if ($amountPerPiece < 0) {
        return ['success' => false, 'message' => 'Amount per piece must be valid.'];
    }

    if (!in_array($paymentStatus, ['paid', 'unpaid'], true)) {
        return ['success' => false, 'message' => 'Invalid payment status.'];
    }

    if (!in_array($paymentMethod, ['cash', 'card'], true)) {
        return ['success' => false, 'message' => 'Invalid payment method.'];
    }

    $allowedIncomingStatuses = [
        'Order Dispatched',
        'In Transit',
        'Received at Warehouse',
    ];

    $incomingStatusMap = [
        'order_dispatched' => 'Order Dispatched',
        'in_transit' => 'In Transit',
        'received' => 'Received at Warehouse',
    ];

    if (isset($incomingStatusMap[$incomingStatus])) {
        $incomingStatus = $incomingStatusMap[$incomingStatus];
    }

    if ($movementType === 'in' && !in_array($incomingStatus, $allowedIncomingStatuses, true)) {
        return ['success' => false, 'message' => 'Invalid incoming stock status.'];
    }

    if ($movementType === 'out') {
        $incomingStatus = null;
    }

    $totalAmount = round($amountPerPiece * $quantity, 2);
    $reference = inventra_generate_stock_reference();

    try {
        $conn->beginTransaction();

        $productStmt = $conn->prepare('SELECT id, quantity FROM products WHERE id = ?');
        $productStmt->execute([$productId]);
        $product = $productStmt->fetch(PDO::FETCH_ASSOC);

        if (!$product) {
            $conn->rollBack();
            return ['success' => false, 'message' => 'Product not found.'];
        }

        $currentQuantity = (int)$product['quantity'];

        if ($movementType === 'out' && $quantity > $currentQuantity) {
            $conn->rollBack();
            return ['success' => false, 'message' => 'Stock out quantity is greater than available stock.'];
        }

        $newQuantity = $movementType === 'in'
            ? $currentQuantity + $quantity
            : $currentQuantity - $quantity;

        $insertStmt = $conn->prepare("
            INSERT INTO stock_movements (
                reference,
                product_id,
                user_id,
                movement_type,
                quantity,
                notes,
                full_name,
                contact,
                amount_per_piece,
                total_amount,
                payment_status,
                payment_method,
                incoming_status,
                movement_status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");

        $insertStmt->execute([
            $reference,
            $productId,
            $userId,
            $movementType,
            $quantity,
            $notes !== '' ? $notes : null,
            $fullName,
            $contact,
            $amountPerPiece,
            $totalAmount,
            $paymentStatus,
            $paymentMethod,
            $incomingStatus,
            $incomingStatus,
        ]);

        $updateStmt = $conn->prepare('UPDATE products SET quantity = ? WHERE id = ?');
        $updateStmt->execute([$newQuantity, $productId]);

        $conn->commit();

        return [
            'success' => true,
            'message' => 'Stock movement recorded successfully.',
            'reference' => $reference,
            'new_quantity' => $newQuantity,
        ];
    } catch (Throwable $e) {
        if ($conn->inTransaction()) {
            $conn->rollBack();
        }

        return [
            'success' => false,
            'message' => 'Failed to record stock movement.',
            'error' => $e->getMessage(),
        ];
    }
}
