<?php

function inventra_ensure_stock_movements_table(PDO $conn): void
{
    $sql = "
        CREATE TABLE IF NOT EXISTS stock_movements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference VARCHAR(50) NOT NULL UNIQUE,
            product_id INTEGER NOT NULL,
            movement_type VARCHAR(10) NOT NULL CHECK (movement_type IN ('in', 'out')),
            quantity INTEGER NOT NULL,
            notes TEXT NULL,
            full_name VARCHAR(150) NULL,
            contact VARCHAR(50) NULL,
            amount_per_piece DECIMAL(10,2) NOT NULL DEFAULT 0,
            total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
            payment_status VARCHAR(10) NOT NULL DEFAULT 'paid' CHECK (payment_status IN ('paid', 'unpaid')),
            payment_method VARCHAR(10) NOT NULL DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card')),
            incoming_status VARCHAR(50) NULL,
            movement_status VARCHAR(50) NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_stock_movements_product
                FOREIGN KEY (product_id) REFERENCES products(id)
                ON DELETE CASCADE
        )
    ";

    $conn->exec($sql);
    $conn->exec('CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id_created_at ON stock_movements (product_id, created_at)');
}

function inventra_generate_stock_reference(): string
{
    return 'STK-' . date('YmdHis') . '-' . strtoupper(bin2hex(random_bytes(2)));
}
