<?php

require_once __DIR__ . '/../config/database.php';

$db = Database::connect();

$statements = [
    "DROP TABLE IF EXISTS ai_reorder_marks CASCADE",
    "DROP TABLE IF EXISTS ai_forecasts CASCADE",
    "DROP TABLE IF EXISTS stock_movements CASCADE",
    "DROP TABLE IF EXISTS notifications CASCADE",
    "DROP TABLE IF EXISTS password_resets CASCADE",
    "DROP TABLE IF EXISTS admin_password_history CASCADE",
    "DROP TABLE IF EXISTS products CASCADE",
    "DROP TABLE IF EXISTS users CASCADE",
    "DROP TABLE IF EXISTS categories CASCADE",
    "DROP TABLE IF EXISTS admin CASCADE",
    <<<'SQL'
CREATE TABLE admin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(191) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'admin',
    phone VARCHAR(30),
    avatar VARCHAR(255),
    notify_low_stock BOOLEAN NOT NULL DEFAULT TRUE,
    notify_weekly_summary BOOLEAN NOT NULL DEFAULT TRUE
)
SQL,
    <<<'SQL'
INSERT INTO admin (id, full_name, email, password_hash, role, phone, avatar, notify_low_stock, notify_weekly_summary) VALUES
(1, 'Swornim Sanjel', 'xettrikenzon@gmail.com', '$2y$10$X7cvTbJ.Gnq42UP.cbfjjOQNZckdtBkvzWyBRi9W6pYUdZdLpL.Ha', 'admin', '9866266301', 'public/uploads/images/profile/admin_1_6ab7397040d167fc.jpg', TRUE, FALSE)
SQL,
    <<<'SQL'
CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
SQL,
    <<<'SQL'
INSERT INTO categories (id, name, description, created_at) VALUES
(1, 'Electronics', 'Electronic office equipment', '2026-04-12 08:07:35'),
(2, 'Accessories', 'Computer and desk accessories', '2026-04-12 08:07:35'),
(3, 'Furniture', 'Office furniture and fixtures', '2026-04-12 08:07:35'),
(4, 'Food', 'any food that u want', '2026-04-12 18:05:42'),
(5, 'Clothes', 'luxury', '2026-04-17 13:33:52')
SQL,
    <<<'SQL'
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(30),
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'staff' CHECK (role IN ('admin', 'staff')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    avatar VARCHAR(255),
    notify_low_stock BOOLEAN NOT NULL DEFAULT TRUE,
    notify_weekly_summary BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
SQL,
    <<<'SQL'
INSERT INTO users (id, full_name, username, email, phone, password, role, status, avatar, notify_low_stock, notify_weekly_summary, created_at) VALUES
(6, 'Swornim Xettri', 'csm_swornim', 'scalestro.work@gmail.com', NULL, '$2y$10$QOYjPQ.OK5NtUJjvCERVlex5rduoh0KTl1RPICsk8BYHm0EI2Y3.C', 'staff', 'active', NULL, TRUE, TRUE, '2026-04-17 13:20:55'),
(7, 'Dipana Shrestha', 'dipana', 'shresthadeepana1@gmail.com', NULL, '$2y$10$A5Wm7Vmfy58jsqhaxuHAqO1UywLojFi.ta8zMRIO5wmmf1Vvpxwpi', 'admin', 'active', NULL, TRUE, TRUE, '2026-04-17 13:23:42'),
(8, 'Sushant Sapkota', 'sushant', 'sushantsapkota2061@gmail.com', NULL, '$2y$10$AX22EPyOf4OLSnCLTCuGyutMcPE1kXB9wv5YrNIskn77jRsonPNPa', 'admin', 'active', NULL, TRUE, TRUE, '2026-04-17 13:26:12'),
(9, 'Suvekshya Adhikari', 'suvekshya', 'adhikarisuvekshya897@gmail.com', NULL, '$2y$10$1VNIp3iiKbFz9A8q.MzJ2evqNgnQ1QRkCQeTdPdJ3ni2hVAAl7OEy', 'staff', 'active', NULL, TRUE, TRUE, '2026-04-17 13:26:41'),
(10, 'Shirish Gurung', 'shirish', 'shirishgurung1224@gmail.com', NULL, '$2y$10$6G3ZKRKrAGASLwxLZy14SeGJc2v3lFstvg3lp5JZsWPNgfr7CsA6.', 'admin', 'active', NULL, TRUE, TRUE, '2026-04-17 13:27:29')
SQL,
    <<<'SQL'
CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    qty INTEGER NOT NULL DEFAULT 0,
    unit_price DECIMAL(10,2) NOT NULL DEFAULT 0,
    lower_limit INTEGER NOT NULL DEFAULT 0,
    upper_limit INTEGER NOT NULL DEFAULT 0,
    image VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
)
SQL,
    "CREATE INDEX idx_products_category_id ON products (category_id)",
    <<<'SQL'
INSERT INTO products (id, category_id, name, category, qty, unit_price, lower_limit, upper_limit, image, description, created_at, updated_at) VALUES
(1, 1, 'MacBook Pro 14" M2', 'Electronics', 4, 285000.00, 5, 12, 'public/uploads/images/products/product_1776016635_12587dd2.webp', 'Apple laptop for office and development work', '2026-04-12 08:07:35', '2026-04-12 17:57:15'),
(2, 2, 'Logitech MX Master 3S', 'Accessories', 0, 14500.00, 3, 15, NULL, 'Wireless productivity mouse', '2026-04-12 08:07:35', '2026-04-12 08:07:35'),
(3, 2, 'Acer Predator Helios Neo 16', 'Accessories', 8, 240000.00, 4, 16, 'public/uploads/images/products/product_1776016106_c73dfb0f.webp', '16 inch high end gaming pc with 340w battery, rtx 4060, 16gb ram and 1tb ssd in built with 3d fans', '2026-04-12 08:07:35', '2026-04-12 17:48:26'),
(4, 3, 'Ergonomic Chair', 'Furniture', 28, 18500.00, 5, 30, NULL, 'Adjustable office chair with lumbar support', '2026-04-12 08:07:35', '2026-04-13 04:39:10'),
(5, 1, 'USB-C Docking Station', 'Electronics', 22, 9500.00, 6, 25, NULL, 'Docking station for laptops and dual-display setups', '2026-04-12 08:07:35', '2026-04-12 08:07:35'),
(6, 4, 'Muscle Blaze Protein', 'Food', 10, 18000.00, 20, 100, 'public/uploads/images/products/product_1776017203_2a59c701.webp', 'MB Protein Powder for gym freaks and body builders for your day to day protein intake goal!', '2026-04-12 18:06:43', '2026-04-12 18:06:43'),
(7, 4, 'Lwang Black', 'Food', 20, 1899.00, 12, 45, 'public/uploads/images/products/product_1776017565_8df78432.webp', 'Organic made in Nepal coffee with lwang - a traditional herb mixed for a better and healthier option', '2026-04-12 18:12:45', '2026-04-12 18:12:45'),
(8, 1, 'iPhone 17 Pro Max', 'Electronics', 300, 275000.00, 45, 500, 'public/uploads/images/products/product_1776017626_13704819.webp', 'best value for money from apple that exists till now', '2026-04-12 18:13:46', '2026-04-12 18:13:46'),
(9, 5, 'Louis Vuitton Polos', 'Clothes', 34, 35000.00, 5, 40, 'public/uploads/images/products/product_1776433098_660eeffa.jpg', 'luxury brand collections', '2026-04-17 13:33:52', '2026-04-17 13:38:18'),
(10, 1, 'Macbook Pro M5 Chip', 'Electronics', 45, 374999.00, 10, 50, 'public/uploads/images/products/product_1776433852_bca79c64.webp', 'Apple MacBook Pro M5 Chip (14.2" (3024 x 1964) Liquid Retina XDR Display | 16/24GB Unified Memory | 512GB/1TB SSD Storage | 10-Core CPU | 10-Core GPU | 16-Core Neural Engine | MacOS | 1 Year Apple International Warranty)', '2026-04-17 13:50:52', '2026-04-17 13:50:52')
SQL,
    <<<'SQL'
CREATE TABLE admin_password_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_password_history_admin FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE
)
SQL,
    "CREATE INDEX idx_admin_password_history_admin_id ON admin_password_history (admin_id)",
    <<<'SQL'
INSERT INTO admin_password_history (id, admin_id, password_hash, changed_at) VALUES
(1, 1, '$2y$10$372WvB9JUch0B7aLZdnRiugFLR4bYKxhw.XuU7LWcRs8Jy9GCSHdW', '2026-04-12 14:36:14'),
(2, 1, '$2y$10$vkp.42ygp0Ip8gDEFHihcuR2M.0w16.IahHWVxHVvLGb9zQyB4sIe', '2026-04-13 09:05:57'),
(3, 1, '$2y$10$GUenCRP9J4I.Qy/Snm3vCOVoYtLoBN2sfbIclON3828SmdDED7I7K', '2026-04-13 09:09:07'),
(4, 1, '$2y$10$vPBWTtUlO1YhZFqvpzYYdOukhHoiBzxr1tM7VVhfRvs1IbsHL8zSO', '2026-04-22 12:49:31')
SQL,
    <<<'SQL'
CREATE TABLE password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    email VARCHAR(191) NOT NULL,
    otp_code VARCHAR(6) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    reset_token VARCHAR(255),
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL
)
SQL,
    "CREATE INDEX idx_password_resets_email_status_created ON password_resets (email, is_verified, expires_at, created_at)",
    "CREATE INDEX idx_password_resets_reset_token ON password_resets (reset_token)",
    <<<'SQL'
INSERT INTO password_resets (id, user_id, email, otp_code, attempts, is_verified, reset_token, expires_at, verified_at, created_at, updated_at) VALUES
(1, 1, 'xettrikenzon@gmail.com', '691730', 0, FALSE, NULL, '2026-04-12 14:29:16', NULL, '2026-04-12 14:19:16', '2026-04-12 14:19:16'),
(2, 1, 'xettrikenzon@gmail.com', '701289', 0, TRUE, '133372582b152fd043a04f69c026828dfb59f63a16641cd991edfac3a70b934e', '2026-04-12 14:45:43', '2026-04-12 14:36:00', '2026-04-12 14:35:43', '2026-04-12 14:36:00'),
(3, 1, 'xettrikenzon@gmail.com', '230609', 0, TRUE, '628ddf22d5152d2729add80cc1ba33ac8e3802af8d4b087d5844f2fede3e6b83', '2026-04-13 09:14:05', '2026-04-13 09:05:41', '2026-04-13 09:04:05', '2026-04-13 09:05:41'),
(4, 1, 'xettrikenzon@gmail.com', '368292', 0, FALSE, NULL, '2026-04-13 09:17:38', NULL, '2026-04-13 09:07:38', '2026-04-13 09:07:38'),
(5, 1, 'xettrikenzon@gmail.com', '825064', 0, TRUE, 'ec5a4dafb6e035f394c96dff3da9c7d280febbd7c3ffc8936f33121b17e532d8', '2026-04-13 09:18:38', '2026-04-13 09:08:55', '2026-04-13 09:08:38', '2026-04-13 09:08:55'),
(6, 1, 'xettrikenzon@gmail.com', '837063', 0, FALSE, NULL, '2026-04-13 10:38:39', NULL, '2026-04-13 10:28:39', '2026-04-13 10:28:39'),
(7, 1, 'xettrikenzon@gmail.com', '269533', 0, FALSE, NULL, '2026-04-17 13:42:02', NULL, '2026-04-17 13:32:02', '2026-04-17 13:32:02'),
(8, 2, 'dipanashrestha891@gmail.com', '265351', 0, FALSE, NULL, '2026-04-17 13:44:58', NULL, '2026-04-17 13:34:58', '2026-04-17 13:34:58'),
(9, 3, 'shirishgurung1224@gmail.com', '404400', 0, FALSE, NULL, '2026-04-17 13:52:23', NULL, '2026-04-17 13:42:23', '2026-04-17 13:42:23'),
(10, 3, 'shirishgurung1224@gmail.com', '956520', 0, FALSE, NULL, '2026-04-17 16:38:18', NULL, '2026-04-17 16:28:18', '2026-04-17 16:28:18'),
(11, 3, 'shirishgurung1224@gmail.com', '703468', 0, FALSE, NULL, '2026-04-17 16:38:24', NULL, '2026-04-17 16:28:24', '2026-04-17 16:28:24'),
(12, 4, 'adhikarisuvekshya897@gmail.com', '176748', 0, FALSE, NULL, '2026-04-17 16:38:49', NULL, '2026-04-17 16:28:49', '2026-04-17 16:28:49'),
(13, 4, 'adhikarisuvekshya897@gmail.com', '475497', 0, FALSE, NULL, '2026-04-17 16:38:56', NULL, '2026-04-17 16:28:56', '2026-04-17 16:28:56'),
(14, 4, 'adhikarisuvekshya897@gmail.com', '947111', 0, FALSE, NULL, '2026-04-17 16:39:09', NULL, '2026-04-17 16:29:09', '2026-04-17 16:29:09'),
(15, 4, 'adhikarisuvekshya897@gmail.com', '493610', 0, FALSE, NULL, '2026-04-17 16:39:12', NULL, '2026-04-17 16:29:12', '2026-04-17 16:29:12'),
(16, 7, 'shresthadeepana1@gmail.com', '531813', 0, FALSE, NULL, '2026-04-18 18:54:39', NULL, '2026-04-18 18:44:39', '2026-04-18 18:44:39'),
(17, 7, 'shresthadeepana1@gmail.com', '324000', 0, FALSE, NULL, '2026-04-18 18:54:47', NULL, '2026-04-18 18:44:47', '2026-04-18 18:44:47'),
(18, 8, 'sushantsapkota2061@gmail.com', '116374', 0, FALSE, NULL, '2026-04-18 18:55:01', NULL, '2026-04-18 18:45:01', '2026-04-18 18:45:01'),
(19, 8, 'sushantsapkota2061@gmail.com', '232808', 0, FALSE, NULL, '2026-04-18 18:55:08', NULL, '2026-04-18 18:45:08', '2026-04-18 18:45:08'),
(20, 9, 'adhikarisuvekshya897@gmail.com', '954701', 0, FALSE, NULL, '2026-04-18 18:55:32', NULL, '2026-04-18 18:45:32', '2026-04-18 18:45:32'),
(21, 9, 'adhikarisuvekshya897@gmail.com', '399790', 0, FALSE, NULL, '2026-04-18 18:55:38', NULL, '2026-04-18 18:45:38', '2026-04-18 18:45:38'),
(22, 1, 'xettrikenzon@gmail.com', '525621', 0, TRUE, 'b0056148fc061bb3ca6a08d8b94257d9c9291127f73b57ccf7b1563b28a41c85', '2026-04-19 14:41:57', '2026-04-19 14:32:42', '2026-04-19 14:31:57', '2026-04-19 14:32:42'),
(23, 1, 'xettrikenzon@gmail.com', '112113', 0, TRUE, 'f05e5a8a701e3eed378a96ca9d215eb198d5c56ca1d588dca89a9ed5631a150c', '2026-04-22 12:58:36', '2026-04-22 12:49:03', '2026-04-22 12:48:36', '2026-04-22 12:49:03')
SQL,
    <<<'SQL'
CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_admin FOREIGN KEY (user_id) REFERENCES admin(id) ON DELETE CASCADE
)
SQL,
    "CREATE INDEX idx_notifications_user_id_created_at ON notifications (user_id, created_at)",
    "CREATE INDEX idx_notifications_user_id_is_read ON notifications (user_id, is_read)",
    <<<'SQL'
INSERT INTO notifications (id, user_id, type, message, is_read, created_at) VALUES
(1, 1, 'low_stock', 'Low Stock: MacBook Pro 14" M2 is below threshold (4 remaining).', TRUE, '2026-04-12 13:42:35'),
(2, 1, 'new_user', 'New user accounts are ready for review.', TRUE, '2026-04-12 12:52:35'),
(3, 1, 'system_update', 'Merged integration database setup completed successfully.', TRUE, '2026-04-11 13:52:35')
SQL,
    <<<'SQL'
CREATE TABLE stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(50) NOT NULL UNIQUE,
    product_id INTEGER NOT NULL,
    movement_type VARCHAR(10) NOT NULL CHECK (movement_type IN ('in', 'out')),
    quantity INTEGER NOT NULL,
    notes TEXT,
    full_name VARCHAR(150),
    contact VARCHAR(50),
    amount_per_piece DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(10) NOT NULL DEFAULT 'paid' CHECK (payment_status IN ('paid', 'unpaid')),
    payment_method VARCHAR(10) NOT NULL DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card')),
    incoming_status VARCHAR(50),
    movement_status VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    status_updated_at TIMESTAMP NULL,
    status_updated_by INTEGER NULL,
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
)
SQL,
    "CREATE INDEX idx_stock_movements_product_id_created_at ON stock_movements (product_id, created_at)",
    <<<'SQL'
INSERT INTO stock_movements (id, reference, product_id, movement_type, quantity, notes, full_name, contact, amount_per_piece, total_amount, payment_status, payment_method, incoming_status, movement_status, created_at, updated_at, status_updated_at, status_updated_by) VALUES
(1, 'STK-TEST-001', 1, 'out', 1, 'Initial sample stock-out entry', 'Sample Customer', '9800000001', 285000.00, 285000.00, 'paid', 'cash', NULL, 'delivered', '2026-04-12 17:25:51', '2026-04-13 04:46:22', NULL, NULL),
(2, 'STK-TEST-002', 5, 'in', 3, 'Initial sample stock-in entry', 'Sample Supplier', '9800000002', 9500.00, 28500.00, 'unpaid', 'card', 'in_transit', NULL, '2026-04-12 17:25:51', '2026-04-13 04:46:22', NULL, NULL),
(3, 'STK-20260413063910-4CBA', 4, 'in', 10, 'new stock added 10 more pieces', 'Swornim Sanjel', '9866266301', 18500.00, 185000.00, 'paid', 'card', 'in_transit', '', '2026-04-13 04:39:10', '2026-04-13 04:46:38', NULL, NULL)
SQL,
    <<<'SQL'
CREATE TABLE ai_forecasts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    current_stock INTEGER NOT NULL,
    predicted_demand INTEGER NOT NULL,
    suggested_reorder_quantity INTEGER NOT NULL,
    forecast_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_forecasts_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_ai_forecasts_product_forecast_date UNIQUE (product_id, forecast_date)
)
SQL,
    "CREATE INDEX idx_ai_forecasts_forecast_date ON ai_forecasts (forecast_date)",
    <<<'SQL'
CREATE TABLE ai_reorder_marks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    marked_by_admin_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'marked',
    marked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_reorder_marks_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_reorder_marks_admin FOREIGN KEY (marked_by_admin_id) REFERENCES admin(id) ON DELETE CASCADE,
    CONSTRAINT uq_ai_reorder_marks_product UNIQUE (product_id)
)
SQL,
    "CREATE INDEX idx_ai_reorder_marks_status_marked_at ON ai_reorder_marks (status, marked_at)",
    "SELECT setval(pg_get_serial_sequence('admin', 'id'), COALESCE((SELECT MAX(id) FROM admin), 1), true)",
    "SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1), true)",
    "SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true)",
    "SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1), true)",
    "SELECT setval(pg_get_serial_sequence('admin_password_history', 'id'), COALESCE((SELECT MAX(id) FROM admin_password_history), 1), true)",
    "SELECT setval(pg_get_serial_sequence('password_resets', 'id'), COALESCE((SELECT MAX(id) FROM password_resets), 1), true)",
    "SELECT setval(pg_get_serial_sequence('notifications', 'id'), COALESCE((SELECT MAX(id) FROM notifications), 1), true)",
    "SELECT setval(pg_get_serial_sequence('stock_movements', 'id'), COALESCE((SELECT MAX(id) FROM stock_movements), 1), true)",
    "SELECT setval(pg_get_serial_sequence('ai_forecasts', 'id'), COALESCE((SELECT MAX(id) FROM ai_forecasts), 1), true)",
    "SELECT setval(pg_get_serial_sequence('ai_reorder_marks', 'id'), COALESCE((SELECT MAX(id) FROM ai_reorder_marks), 1), true)",
];

try {
    $db->beginTransaction();

    foreach ($statements as $statement) {
        $db->exec($statement);
    }

    $db->commit();
    echo "PostgreSQL bootstrap completed successfully.\n";
} catch (Throwable $e) {
    if ($db->inTransaction()) {
        $db->rollBack();
    }

    fwrite(STDERR, "Bootstrap failed: " . $e->getMessage() . PHP_EOL);
    exit(1);
}
