<?php

require_once __DIR__ . '/../config/database.php';

/**
 * Notification data access with admin/user recipient support.
 */
class NotificationModel
{
    private const TYPE_META = [
        'low_stock' => [
            'label' => 'Low Stock',
            'icon' => ['variant' => 'warning', 'symbol' => 'warning'],
        ],
        'request_approved' => [
            'label' => 'Request Approved',
            'icon' => ['variant' => 'success', 'symbol' => 'check'],
        ],
        'new_user' => [
            'label' => 'New User',
            'icon' => ['variant' => 'user', 'symbol' => 'user'],
        ],
        'system_update' => [
            'label' => 'System Update',
            'icon' => ['variant' => 'settings', 'symbol' => 'settings'],
        ],
        'security_alert' => [
            'label' => 'Security Alert',
            'icon' => ['variant' => 'shield', 'symbol' => 'shield'],
        ],
    ];

    private PDO $db;

    public function __construct()
    {
        $this->db = Database::connect();
        $this->ensureSchema();
    }

    public function ensureSchema(): void
    {
        $this->db->exec("
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                recipient_source VARCHAR(20) NOT NULL DEFAULT 'admin',
                type VARCHAR(50) NOT NULL,
                title VARCHAR(120) NOT NULL,
                message VARCHAR(255) NOT NULL,
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        ");

        $this->db->exec('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_notifications_admin');
        $this->db->exec("ALTER TABLE notifications ADD COLUMN IF NOT EXISTS recipient_source VARCHAR(20) NOT NULL DEFAULT 'admin'");
        $this->db->exec('ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title VARCHAR(120)');

        $this->db->exec("
            UPDATE notifications
            SET recipient_source = 'admin'
            WHERE recipient_source IS NULL
               OR BTRIM(recipient_source) = ''
        ");

        $this->db->exec("
            UPDATE notifications
            SET
                title = CASE
                    WHEN POSITION(':' IN message) > 0 THEN BTRIM(SPLIT_PART(message, ':', 1))
                    WHEN type = 'low_stock' THEN 'Low Stock'
                    WHEN type = 'request_approved' THEN 'Request Approved'
                    WHEN type = 'new_user' THEN 'New User'
                    WHEN type = 'system_update' THEN 'System Update'
                    WHEN type = 'security_alert' THEN 'Security Alert'
                    ELSE 'Notification'
                END,
                message = CASE
                    WHEN POSITION(':' IN message) > 0 THEN BTRIM(SUBSTRING(message FROM POSITION(':' IN message) + 1))
                    ELSE message
                END
            WHERE title IS NULL
               OR BTRIM(title) = ''
        ");

        $this->db->exec('ALTER TABLE notifications ALTER COLUMN recipient_source SET NOT NULL');
        $this->db->exec('ALTER TABLE notifications ALTER COLUMN title SET NOT NULL');
        $this->db->exec('CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_at ON notifications (recipient_source, user_id, created_at)');
        $this->db->exec('CREATE INDEX IF NOT EXISTS idx_notifications_recipient_is_read ON notifications (recipient_source, user_id, is_read)');
    }

    public function getNotificationsForUser(int $userId, string $source = 'admin', int $limit = 10, int $page = 1): array
    {
        $limit = max(1, min(100, $limit));
        $page = max(1, $page);
        $offset = ($page - 1) * $limit;

        $stmt = $this->db->prepare("
            SELECT id, user_id, recipient_source, type, title, message, is_read, created_at
            FROM notifications
            WHERE user_id = :user_id
              AND recipient_source = :recipient_source
            ORDER BY created_at DESC, id DESC
            LIMIT :limit OFFSET :offset
        ");
        $stmt->bindValue(':user_id', $userId, PDO::PARAM_INT);
        $stmt->bindValue(':recipient_source', $source, PDO::PARAM_STR);
        $stmt->bindValue(':limit', $limit, PDO::PARAM_INT);
        $stmt->bindValue(':offset', $offset, PDO::PARAM_INT);
        $stmt->execute();

        return $stmt->fetchAll() ?: [];
    }

    public function countNotificationsForUser(int $userId, string $source = 'admin'): int
    {
        $stmt = $this->db->prepare("
            SELECT COUNT(*)
            FROM notifications
            WHERE user_id = ?
              AND recipient_source = ?
        ");
        $stmt->execute([$userId, $source]);

        return (int) $stmt->fetchColumn();
    }

    public function countUnreadForUser(int $userId, string $source = 'admin'): int
    {
        $stmt = $this->db->prepare("
            SELECT COUNT(*)
            FROM notifications
            WHERE user_id = ?
              AND recipient_source = ?
              AND is_read = FALSE
        ");
        $stmt->execute([$userId, $source]);

        return (int) $stmt->fetchColumn();
    }

    public function markAllAsReadForUser(int $userId, string $source = 'admin'): int
    {
        $stmt = $this->db->prepare("
            UPDATE notifications
            SET is_read = TRUE
            WHERE user_id = ?
              AND recipient_source = ?
              AND is_read = FALSE
        ");
        $stmt->execute([$userId, $source]);

        return $stmt->rowCount();
    }

    public function markNotificationAsReadForUser(int $notificationId, int $userId, string $source = 'admin'): bool
    {
        $stmt = $this->db->prepare("
            UPDATE notifications
            SET is_read = TRUE
            WHERE id = ?
              AND user_id = ?
              AND recipient_source = ?
        ");
        $stmt->execute([$notificationId, $userId, $source]);

        return $stmt->rowCount() > 0;
    }

    public function createNotification(
        int $userId,
        string $source,
        string $type,
        string $title,
        string $message,
        bool $isRead = false,
        ?string $createdAt = null
    ): int {
        $normalizedType = $this->normalizeType($type);

        if ($normalizedType === null) {
            throw new InvalidArgumentException('Unsupported notification type: ' . $type);
        }

        $source = trim(strtolower($source));
        if (!in_array($source, ['admin', 'users'], true)) {
            throw new InvalidArgumentException('Unsupported notification source: ' . $source);
        }

        $title = trim($title);
        $message = trim($message);

        if ($title === '') {
            $title = $this->humanizeType($normalizedType);
        }

        if ($message === '') {
            $message = $title;
        }

        $stmt = $this->db->prepare('
            INSERT INTO notifications (user_id, recipient_source, type, title, message, is_read, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            RETURNING id
        ');
        $stmt->execute([
            $userId,
            $source,
            $normalizedType,
            $title,
            $message,
            $isRead ? '1' : '0',
            $createdAt ?: date('Y-m-d H:i:s'),
        ]);

        return (int) $stmt->fetchColumn();
    }

    public function createNotificationIfMissing(
        int $userId,
        string $source,
        string $type,
        string $title,
        string $message,
        ?int $windowMinutes = null,
        bool $isRead = false
    ): ?int {
        if ($this->hasMatchingNotification($userId, $source, $type, $title, $message, $windowMinutes)) {
            return null;
        }

        return $this->createNotification($userId, $source, $type, $title, $message, $isRead);
    }

    public function hasMatchingNotification(
        int $userId,
        string $source,
        string $type,
        string $title,
        string $message,
        ?int $windowMinutes = null
    ): bool {
        $normalizedType = $this->normalizeType($type);

        if ($normalizedType === null) {
            return false;
        }

        $sql = "
            SELECT 1
            FROM notifications
            WHERE user_id = ?
              AND recipient_source = ?
              AND type = ?
              AND title = ?
              AND message = ?
        ";
        $params = [$userId, trim(strtolower($source)), $normalizedType, trim($title), trim($message)];

        if ($windowMinutes !== null && $windowMinutes > 0) {
            $sql .= ' AND created_at >= ?';
            $params[] = date('Y-m-d H:i:s', strtotime('-' . $windowMinutes . ' minutes'));
        }

        $sql .= ' LIMIT 1';

        $stmt = $this->db->prepare($sql);
        $stmt->execute($params);

        return (bool) $stmt->fetchColumn();
    }

    public function buildNotificationViewData(array $rows): array
    {
        $mapped = [];

        foreach ($rows as $row) {
            $title = trim((string) ($row['title'] ?? ''));
            $message = trim((string) ($row['message'] ?? ''));

            if ($title === '') {
                $legacy = $this->splitLegacyMessage($message, (string) ($row['type'] ?? ''));
                $title = $legacy['title'];
                $message = $legacy['message'];
            }

            $mapped[] = [
                'id' => (int) $row['id'],
                'user_id' => (int) ($row['user_id'] ?? 0),
                'recipient_source' => (string) ($row['recipient_source'] ?? 'admin'),
                'type' => (string) $row['type'],
                'title' => $title,
                'message' => $message,
                'body' => $message,
                'full_message' => $message !== '' ? $title . ': ' . $message : $title,
                'is_read' => (bool) $row['is_read'],
                'created_at' => (string) $row['created_at'],
                'relative_time' => $this->formatRelativeTime((string) $row['created_at']),
                'icon' => $this->iconForType((string) $row['type']),
            ];
        }

        return $mapped;
    }

    public function isSupportedType(string $type): bool
    {
        return $this->normalizeType($type) !== null;
    }

    private function formatRelativeTime(string $createdAt): string
    {
        $timestamp = strtotime($createdAt);

        if ($timestamp === false) {
            return 'Just now';
        }

        $diff = max(0, time() - $timestamp);

        if ($diff < 60) {
            return 'Just now';
        }

        $minutes = (int) floor($diff / 60);
        if ($minutes < 60) {
            return $minutes . ' minute' . ($minutes === 1 ? '' : 's') . ' ago';
        }

        $hours = (int) floor($minutes / 60);
        if ($hours < 24) {
            return $hours . ' hour' . ($hours === 1 ? '' : 's') . ' ago';
        }

        $days = (int) floor($hours / 24);
        if ($days === 1) {
            return 'Yesterday at ' . date('g:i A', $timestamp);
        }

        if ($days < 7) {
            return $days . ' day' . ($days === 1 ? '' : 's') . ' ago';
        }

        $weeks = (int) floor($days / 7);
        if ($weeks < 5) {
            return $weeks . ' week' . ($weeks === 1 ? '' : 's') . ' ago';
        }

        return date('M j, Y', $timestamp);
    }

    private function iconForType(string $type): array
    {
        $normalizedType = $this->normalizeType($type);

        if ($normalizedType === null) {
            return ['variant' => 'info', 'symbol' => 'settings'];
        }

        return self::TYPE_META[$normalizedType]['icon'];
    }

    private function splitLegacyMessage(string $message, string $type): array
    {
        $parts = explode(':', $message, 2);

        if (count($parts) === 2) {
            return [
                'title' => trim($parts[0]),
                'message' => trim($parts[1]),
            ];
        }

        return [
            'title' => $this->humanizeType($type),
            'message' => trim($message),
        ];
    }

    private function humanizeType(string $type): string
    {
        $normalizedType = $this->normalizeType($type);

        if ($normalizedType === null) {
            return 'Notification';
        }

        return self::TYPE_META[$normalizedType]['label'];
    }

    private function normalizeType(string $type): ?string
    {
        $type = strtolower(trim(str_replace([' ', '-'], '_', $type)));

        return array_key_exists($type, self::TYPE_META) ? $type : null;
    }
}
