<?php

require_once __DIR__ . '/../config/database.php';

class UserManagementModel
{
    private PDO $db;

    public function __construct()
    {
        $this->db = Database::connect();
    }

    public function ensureSchema(): void
    {
        $this->db->exec("
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name VARCHAR(100) NOT NULL,
                username VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL,
                password VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL DEFAULT 'staff',
                status VARCHAR(20) NOT NULL DEFAULT 'active',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT chk_users_role CHECK (role IN ('admin', 'staff')),
                CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive')),
                CONSTRAINT uniq_users_username UNIQUE (username),
                CONSTRAINT uniq_users_email UNIQUE (email)
            )
        ");

        $this->ensureColumnExists('phone', 'ALTER TABLE users ADD COLUMN phone VARCHAR(30)');
        $this->ensureColumnExists('avatar', 'ALTER TABLE users ADD COLUMN avatar VARCHAR(255)');
        $this->ensureColumnExists('notify_low_stock', 'ALTER TABLE users ADD COLUMN notify_low_stock BOOLEAN NOT NULL DEFAULT TRUE');
        $this->ensureColumnExists('notify_weekly_summary', 'ALTER TABLE users ADD COLUMN notify_weekly_summary BOOLEAN NOT NULL DEFAULT TRUE');
    }

    public function getUsers(string $role = '', string $status = ''): array
    {
        $sql = 'SELECT id, full_name, username, email, role, status, created_at FROM users WHERE 1=1';
        $params = [];

        if ($role !== '' && $role !== 'all') {
            $sql .= ' AND role = ?';
            $params[] = $role === 'user' ? 'staff' : $role;
        }

        if ($status !== '' && $status !== 'all') {
            $sql .= ' AND status = ?';
            $params[] = $status;
        }

        $sql .= ' ORDER BY created_at DESC, id DESC';

        $stmt = $this->db->prepare($sql);
        $stmt->execute($params);
        $rows = $stmt->fetchAll();

        return array_map([$this, 'normalizeUser'], $rows);
    }

    public function createUser(string $fullName, string $email, string $username, string $password, string $role): int
    {
        $stmt = $this->db->prepare('
            INSERT INTO users (full_name, username, email, password, role, status, created_at)
            VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
            RETURNING id
        ');
        $stmt->execute([
            $fullName,
            $username,
            $email,
            password_hash($password, PASSWORD_BCRYPT),
            $this->normalizeRoleInput($role),
            'active',
        ]);

        return (int) $stmt->fetchColumn();
    }

    public function updateUser(int $id, string $fullName, string $email, string $username, string $role): bool
    {
        $stmt = $this->db->prepare('
            UPDATE users
            SET full_name = ?, username = ?, email = ?, role = ?
            WHERE id = ?
        ');

        return $stmt->execute([
            $fullName,
            $username,
            $email,
            $this->normalizeRoleInput($role),
            $id,
        ]);
    }

    public function deleteUser(int $id): bool
    {
        $stmt = $this->db->prepare('DELETE FROM users WHERE id = ?');
        return $stmt->execute([$id]);
    }

    public function toggleStatus(int $id): ?string
    {
        $stmt = $this->db->prepare('SELECT status FROM users WHERE id = ? LIMIT 1');
        $stmt->execute([$id]);
        $row = $stmt->fetch();

        if (!$row) {
            return null;
        }

        $newStatus = ($row['status'] ?? 'active') === 'active' ? 'inactive' : 'active';

        $update = $this->db->prepare('UPDATE users SET status = ? WHERE id = ?');
        $update->execute([$newStatus, $id]);

        return $newStatus;
    }

    public function existsByUsernameOrEmail(string $username, string $email, ?int $excludeId = null): bool
    {
        $sql = 'SELECT id FROM users WHERE (username = ? OR email = ?)';
        $params = [$username, $email];

        if ($excludeId !== null) {
            $sql .= ' AND id <> ?';
            $params[] = $excludeId;
        }

        $sql .= ' LIMIT 1';

        $stmt = $this->db->prepare($sql);
        $stmt->execute($params);

        return (bool) $stmt->fetch();
    }

    public function findById(int $id): ?array
    {
        $stmt = $this->db->prepare('
            SELECT id, full_name, username, email, role, status, created_at
            FROM users
            WHERE id = ?
            LIMIT 1
        ');
        $stmt->execute([$id]);
        $row = $stmt->fetch();

        return $row ? $this->normalizeUser($row) : null;
    }

    private function normalizeRoleInput(string $role): string
    {
        return strtolower(trim($role)) === 'admin' ? 'admin' : 'staff';
    }

    private function normalizeUser(array $user): array
    {
        $role = $this->normalizeRoleInput((string) ($user['role'] ?? 'staff'));

        return [
            'id' => (int) $user['id'],
            'full_name' => (string) ($user['full_name'] ?? ''),
            'username' => (string) ($user['username'] ?? ''),
            'email' => (string) ($user['email'] ?? ''),
            'role' => $role,
            'display_role' => $role === 'admin' ? 'Admin' : 'User',
            'status' => (string) ($user['status'] ?? 'active'),
            'created_at' => (string) ($user['created_at'] ?? ''),
        ];
    }

    private function ensureColumnExists(string $column, string $sql): void
    {
        if (!Database::columnExists('users', $column)) {
            $this->db->exec($sql);
        }
    }
}
